### PR TITLE
fix: skip convert empty urls

### LINKED ISSUE #444: Maybe bug with empty url
`url("")` => `url(.)`, i think it is invalid modification

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #444

### CODE REVIEW

File: packages/postcss-normalize-url/src/index.js [hunk 1]
```diff
@@ -52,7 +52,7 @@ function transformDecl (decl, opts) {
             return false;
         }
 
-        if (!~url.value.indexOf('chrome-extension')) {
+        if (url.value.length !== 0 && !~url.value.indexOf('chrome-extension')) {
```
Comment (andyjansson) [inline packages/postcss-normalize-url/src/index.js]: Given #463, this should take into account other extensions as well.
